/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorCuarto;
import Controlador.ControladorModulo;
import Modelos.Cuarto;
import Modelos.Modulo;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class VentanaModulos extends javax.swing.JFrame   implements ActionListener {

  JButton [][] botones;
  
  private ControladorModulo controladorModulo;
    
   
    public VentanaModulos() {
        initComponents();
        setLocationRelativeTo(this);
        botones = new JButton[3][4];
        controladorModulo = new ControladorModulo();
        cargarBotones();
        validarPosiciones();
       
        
        
    }

    public ControladorModulo getControladorModulo() {
        return controladorModulo;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelModulo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelModuloLayout = new javax.swing.GroupLayout(panelModulo);
        panelModulo.setLayout(panelModuloLayout);
        panelModuloLayout.setHorizontalGroup(
            panelModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        panelModuloLayout.setVerticalGroup(
            panelModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelModulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaModulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaModulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaModulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaModulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VentanaModulos().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelModulo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
     for (int i =0;i<botones.length;i++){
           for (int j =0;j<botones[i].length;j++){
               if (e.getSource().equals(botones[i][j])){
                   Modulo modulo = controladorModulo.obtenerModulo(i,j);
                   if (modulo.getEstado().equals(Modulo.DISPONIBLE)){
                       VentanaCuarto ventanaCuarto = new VentanaCuarto(this);  //VENTANA DONDE SE CREA EL PERRRO 
                       ventanaCuarto.setVisible(true);
                       this.dispose();
                       
                       
                       
                               
                  
                        } else {
                        
                       String mensaje = " Este modulo ya tiene todos los cuartos ocupados con caninos y excedio el limite";
                   
                       
                       JOptionPane.showMessageDialog(null, mensaje);
                       }       
                   }
                       
               }
           }
       
    
        
        
        
        
    }

    private void cargarBotones() {
     int ancho = 90;
        int alto = 90;
        int separado = 100;
        int texto =1 ;
       
        
        for (int i =0;i<botones.length;i++){
            for (int j=0; j<botones[i].length;j++){
                botones[i][j]= new JButton();
                
                //setBounds posX posY ancho y alto 
                botones[i][j].setBounds(    
                (j*ancho + separado),
                        (i*alto + separado ),
                        ancho, alto
                
                );
                
                
                botones[i][j].setText(String.valueOf(texto));
                botones[i][j].addActionListener(this);
                panelModulo.add(botones[i][j]);
                texto++;
              
            }
        }
            
        
        
        
        
        
    }

    private void validarPosiciones() {
         for (int i =0;i<botones.length;i++){
        for (int j =0;j<botones[i].length;j++){
            Modulo modulo = controladorModulo.obtenerModulo(i, j);
            if (modulo.getEstado().equals(modulo.DISPONIBLE)){
                botones[i][j].setBackground(Color.white);
                botones[i][j].setText(Cuarto.DISPONIBLE);
            } else{
                botones [i][j].setBackground(Color.green);
                //botones [i][j].setVisible(false);
                botones[i][j].setText(modulo.getEstado());
               
            }
            
            
            
        } 
     }  
    }
}
