/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorCuarto;
import Excepciones.DocumentoDuplicadoException;
import Excepciones.documentoNoExisteExeption;
import Modelos.Perro;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class VentanaPerro extends javax.swing.JFrame {

    private VentanaCuarto ventanaCuarto;
    private int fila;
    private DefaultTableModel modeloTablaInfoModulo;

    public VentanaPerro(VentanaCuarto ventanaCuarto, int fila) {
        initComponents();
        setLocationRelativeTo(this);
        this.ventanaCuarto = ventanaCuarto;
        this.fila = fila;

        inicializarComboBoxComida();
        inicializarComboBoxEstado();
        mostrarInfoenTabla();
        btnEditar.setEnabled(false);
        btnEliminar.setEnabled(false);

    }

    private void inicializarComboBoxComida() {
        cbComida.removeAllItems();
        cbComida.addItem("Seleccione");
        cbComida.addItem("Cuido");
        cbComida.addItem("solo sopas");
        cbComida.addItem("de sal");
        cbComida.addItem("cuido y de sal");
        cbComida.addItem("sopas y cuido");

    }

    private void inicializarComboBoxEstado() {
        cbEstado.removeAllItems();
        cbEstado.addItem("Seleccione");
        cbEstado.addItem("Enfermo");
        cbEstado.addItem("Aliviado");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPerroo = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        lblNombrecanino = new java.awt.Label();
        lblIdentificador = new java.awt.Label();
        lblEdad = new java.awt.Label();
        lblRaza = new java.awt.Label();
        lblComida = new java.awt.Label();
        lblEstado = new java.awt.Label();
        lblTratamiento = new java.awt.Label();
        txtNombreCanino = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtIdentificador = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtRaza = new javax.swing.JTextField();
        cbComida = new javax.swing.JComboBox<>();
        cbEstado = new javax.swing.JComboBox<>();
        txtTratamiento = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInfoCuartosPerro = new javax.swing.JTable();
        btnVerCuartos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setText("DATOS DEL CANINO:");

        lblNombrecanino.setText("Nombre canino");

        lblIdentificador.setText("Identificador");

        lblEdad.setText("Edad");

        lblRaza.setText("Raza");

        lblComida.setText("Comida");

        lblEstado.setText("Estado");

        lblTratamiento.setText("Tratamiento");

        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });

        cbComida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tablaInfoCuartosPerro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaInfoCuartosPerro);

        btnVerCuartos.setText("Atras/ Ver cuartos");
        btnVerCuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCuartosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPerrooLayout = new javax.swing.GroupLayout(panelPerroo);
        panelPerroo.setLayout(panelPerrooLayout);
        panelPerrooLayout.setHorizontalGroup(
            panelPerrooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPerrooLayout.createSequentialGroup()
                .addGroup(panelPerrooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPerrooLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblNombrecanino, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPerrooLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPerrooLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPerrooLayout.createSequentialGroup()
                        .addGroup(panelPerrooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPerrooLayout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(lblEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPerrooLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelPerrooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRaza, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblComida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEstado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTratamiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblIdentificador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPerrooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelPerrooLayout.createSequentialGroup()
                                .addComponent(cbComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(164, 164, 164)
                                .addComponent(btnVerCuartos))
                            .addComponent(txtTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelPerrooLayout.createSequentialGroup()
                                .addGroup(panelPerrooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreCanino, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelPerrooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelPerrooLayout.createSequentialGroup()
                                        .addGap(118, 118, 118)
                                        .addGroup(panelPerrooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnEditar)
                                            .addComponent(btnEliminar)))
                                    .addGroup(panelPerrooLayout.createSequentialGroup()
                                        .addGap(117, 117, 117)
                                        .addGroup(panelPerrooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnBuscar)
                                            .addGroup(panelPerrooLayout.createSequentialGroup()
                                                .addComponent(btnAgregar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPerrooLayout.setVerticalGroup(
            panelPerrooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPerrooLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPerrooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPerrooLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(panelPerrooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPerrooLayout.createSequentialGroup()
                                .addGroup(panelPerrooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelPerrooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtNombreCanino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnAgregar))
                                    .addComponent(lblNombrecanino, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelPerrooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))
                            .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(panelPerrooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPerrooLayout.createSequentialGroup()
                                .addGroup(panelPerrooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(panelPerrooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelPerrooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnEliminar))
                                    .addComponent(lblRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelPerrooLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(33, 33, 33)
                .addGroup(panelPerrooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelPerrooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnVerCuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelPerrooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelPerrooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPerrooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPerroo, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPerroo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (validarCamposPerro()) {
            JOptionPane.showMessageDialog(null, "recuerda digitar todos los datos para agregar al perro  ");

        } else {

            String nombre = txtNombreCanino.getText();
            String identificador = txtIdentificador.getText();
            int edad = Integer.parseInt(txtEdad.getText());
            String raza = txtRaza.getText();
            String comida = String.valueOf(cbComida.getSelectedItem());
            String estado = String.valueOf(cbEstado.getSelectedIndex());
            String tratamiento = txtTratamiento.getText();
            
           System.out.print(this.fila);

            Perro perro = new Perro(nombre, identificador, edad, raza, comida, estado, tratamiento, this.fila);
            try {
                boolean respuesta = ventanaCuarto.getControladorCuarto().registrarPerro(perro);
                if (respuesta) {
                    JOptionPane.showMessageDialog(null, "El canino fue agregado correctamente al cuarto");
                    limpiarCamposPerro();
                    mostrarInfoenTabla();
                    ventanaCuarto.validate();
                    //ventanaCuarto.setVisible(true);

                    //this.dispose();
                }

            } catch (DocumentoDuplicadoException docuementoDuplicadoException) {
                JOptionPane.showMessageDialog(null, docuementoDuplicadoException.getMessage());

            }

        }


    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:

        if (validarCamposVaciosBuscarYEliminarPerro()) {
            JOptionPane.showMessageDialog(null, "Por favor recuerde digitar el numero de documento para buscar el canino");
        } else {
            String identificador = txtIdentificador.getText();
            Perro auxiliar = ventanaCuarto.getControladorCuarto().buscarPerro(identificador);
            if (auxiliar != null) {

                txtNombreCanino.setText(auxiliar.getNombre());
                txtIdentificador.setText(auxiliar.getIdentificador());
                txtEdad.setText(String.valueOf(auxiliar.getEdad()));
                txtRaza.setText(auxiliar.getRaza());
                String comida = String.valueOf(cbComida.getSelectedItem());
                String estado = String.valueOf(cbEstado.getSelectedItem());
                txtTratamiento.setText(auxiliar.getTratamiento());
                btnEditar.setEnabled(true);
                btnEliminar.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(null, "El canino bajo este documento --->  " + identificador + "  NO existe ");
                txtIdentificador.setText("");
                limpiarCamposPerro();
            }

    }//GEN-LAST:event_btnBuscarActionPerformed

    }
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (validarCamposPerro()) {
            JOptionPane.showMessageDialog(null, "por favor recuerde COMPLETAR TODOS los datos del Canino al editar ");
        } else {

            String nombre = txtNombreCanino.getText();
            String identificador = txtIdentificador.getText();
            int Edad = Integer.parseInt(txtEdad.getText());
            String raza = txtRaza.getText();
            String comida = String.valueOf(cbComida.getSelectedItem());
            String estado = String.valueOf(cbEstado.getSelectedItem());
            String tratamiento = txtTratamiento.getText();

            Perro auxiliarPerro = new Perro(nombre, identificador, Edad, raza, comida, estado, tratamiento, this.fila);
            try {
                ventanaCuarto.getControladorCuarto().editarPerro(auxiliarPerro);
                JOptionPane.showMessageDialog(null, " Se edito CORRECTAMENTE el canino con Identificacion " + identificador);
                limpiarCamposPerro();
                mostrarInfoenTabla();

            } catch (documentoNoExisteExeption documentoNoExisteExeption1) {
                JOptionPane.showMessageDialog(null, documentoNoExisteExeption1.getMessage());
      
            }

        }


    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (validarCamposVaciosBuscarYEliminarPerro()) {
            JOptionPane.showMessageDialog(null, " Recuerda ingresar el numero de identificador del canino ");
        } else {

            String identificador = txtIdentificador.getText();
            boolean respuesta = ventanaCuarto.getControladorCuarto().eliminarPerro(identificador);
            if (respuesta) {
                JOptionPane.showMessageDialog(null, " se elimino CORRECTAMENTE el canino bajo esta identificacion " + identificador);
                limpiarCamposPerro();
                mostrarInfoenTabla();
            } else {
                JOptionPane.showMessageDialog(null, " NO se elimino el canino con el identificador " + identificador);
            }

        }


    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnVerCuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCuartosActionPerformed
        // TODO add your handling code here:
        ventanaCuarto.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_btnVerCuartosActionPerformed

    public boolean validarCamposPerro() {
        String nombre = txtNombreCanino.getText();
        String identificador = txtIdentificador.getText();
        String edadAux = txtEdad.getText();
        String raza = txtRaza.getText();
        int comida = cbComida.getSelectedIndex();
        int estado = cbEstado.getSelectedIndex();
        String tratamiento = txtTratamiento.getText();

        if (nombre.isBlank() || identificador.isBlank() || edadAux.isEmpty() || raza.isEmpty() || comida == 0 || estado == 0 || tratamiento.isBlank()) {
            return true;
        } else {
            int edad = Integer.parseInt(edadAux);
            return false;
        }

    }

    private boolean validarCamposVaciosBuscarYEliminarPerro() {
        String identificador = txtIdentificador.getText();

        if (identificador.isBlank()) {
            return true;
        } else {
            return false;
        }

    }

    public void limpiarCamposPerro() {
        txtNombreCanino.setText("");
        txtIdentificador.setText("");
        txtEdad.setText("");
        txtRaza.setText("");
        cbComida.setSelectedItem("Seleccione");
        cbEstado.setSelectedItem("Seleccione");
        txtTratamiento.setText("");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPerro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPerro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPerro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPerro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnVerCuartos;
    private javax.swing.JComboBox<String> cbComida;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private java.awt.Label label1;
    private java.awt.Label lblComida;
    private java.awt.Label lblEdad;
    private java.awt.Label lblEstado;
    private java.awt.Label lblIdentificador;
    private java.awt.Label lblNombrecanino;
    private java.awt.Label lblRaza;
    private java.awt.Label lblTratamiento;
    private javax.swing.JPanel panelPerroo;
    private javax.swing.JTable tablaInfoCuartosPerro;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtIdentificador;
    private javax.swing.JTextField txtNombreCanino;
    private javax.swing.JTextField txtRaza;
    private javax.swing.JTextField txtTratamiento;
    // End of variables declaration//GEN-END:variables

    private void mostrarInfoenTabla() {
        String[][] tablaCuartoPerros = new String[ventanaCuarto.getControladorCuarto().getLista().size()][8];
        for (int i = 0; i < ventanaCuarto.getControladorCuarto().getLista().size(); i++) {
                       System.out.print("FILAAA" + this.fila);

            if (i == this.fila){
                
                System.out.println("ENTROOOOOOOO");
                                System.out.println(ventanaCuarto.getControladorCuarto().perro(i).getCuarto());

            //String nombre, String identificador, int edad, String raza, String comida, String estado, String tratamiento
            tablaCuartoPerros[i][0] = ventanaCuarto.getControladorCuarto().perro(i).getNombre();
            tablaCuartoPerros[i][1] = ventanaCuarto.getControladorCuarto().perro(i).getIdentificador();
            tablaCuartoPerros[i][2] = String.valueOf(ventanaCuarto.getControladorCuarto().perro(i).getEdad());
            tablaCuartoPerros[i][4] = ventanaCuarto.getControladorCuarto().perro(i).getRaza();
            tablaCuartoPerros[i][5] = ventanaCuarto.getControladorCuarto().perro(i).getComida();
            tablaCuartoPerros[i][6] = ventanaCuarto.getControladorCuarto().perro(i).getEstado();
            tablaCuartoPerros[i][7] = ventanaCuarto.getControladorCuarto().perro(i).getTratamiento();
        
        }else{
                                System.out.println("NOOOO ENTROOOOOOOO");

            }
        }

        tablaInfoCuartosPerro.setModel(new javax.swing.table.DefaultTableModel(
                tablaCuartoPerros,
                new String[]{
                    "Nombre", "Identificador", "Edad", "Raza", "Comida", "Estado", "Tratamiento"
                } 
        ));
    }
}
